### ISSUE TITLE
Meditation Level box and MeditationTimerSetupSVC UI

### ISSUE THREAD

**Issue by DrexelOMS** [DrexelOMS/OvercomingMS#111]
this is the box that will hold the mediation level image and duration label.

If you haven't used the RoundCornersUIView before, All you need to do is make the xib, make a "Main" view you want to have the rounded corners, and make its class RoundCornersUIView 

you can make the view that is has the round corners background be white

**Comment by VincentShaneFinn** [comment]
you can also do the setup page here where these level boxes are dispalyed
