### ISSUE TITLE
Change confirmation screen texts to be grammatically correct.

### ISSUE THREAD

**Issue by DrexelOMS** [DrexelOMS/OvercomingMS#114]
UIViews > Reusable Views > Tracking Modules > ConfirmationSVC

This is in regards to the confirmation screen. Corey wants the top text to start from the bottom, and then as more lines get added, it would then add a second line, but it still vertically align the text to the bottom. And the sub label would basically be vertically aligned top

**Comment by cgl48** [comment]
Vertical align already done. Editted the text on the confirmation screens to be gramatically correct.
