### ISSUE TITLE
Goals UI Views

### ISSUE THREAD

**Issue by VincentShaneFinn** [DrexelOMS/OvercomingMS#209]
![image](https://user-images.githubusercontent.com/44733528/55807206-cdcc3680-5aaf-11e9-95c3-dc2e994c27cb.png)

![image](https://user-images.githubusercontent.com/44733528/56069244-2cafdb00-5d50-11e9-9070-8200e45a2e76.png)

**Comment by DrexelOMS** [comment]
look for the goals folder, there are views for the goals main, the goals modify, and goals box.  basically the box is the button you push in the goals main, and the main and modify views are everything under trophy image.

just pull down issue_209 to start working on it

**Comment by ctd58** [comment]
I implemented the base UI, Corey just needs to finalize it
