### ISSUE TITLE
Find or make a horizontal number picker

### ISSUE THREAD

**Issue by DrexelOMS** [DrexelOMS/OvercomingMS#220]
First check cocoapods to see if there is an example, all you do is add the name to the pod file and run pod install, do this first because if something break you need to come to me

make a HorizontalNumberPickerSVC()

it should have an observer that alerts the delegate whenever the picker stops on a number

![image](https://user-images.githubusercontent.com/44733528/55435235-6ec66900-5567-11e9-870a-96a6eb4e5db5.png)

**Comment by ctd58** [comment]
https://github.com/ink-spot/UPCarouselFlowLayout
