### ISSUE TITLE
Update TrackingProgressBar UI MAIN STORYBOARD EDIT

### ISSUE THREAD

**Issue by VincentShaneFinn** [DrexelOMS/OvercomingMS#24]
go to UI Views > Reusable Views > TrackingProgressBars.
work here on the 2 xib files to make slider, labels, and look the way they do in the design.

Additionally, I created a field so if you go to the main storyboard you can change the colors with the barColor field on each progress bar. You probably wont see the changes in the inspector, but will see it if you run the app. I do not know how to fix this issue, but most things you you can edit in the xib files directly. 

So the check button needs to use that image, colors for each on the main storyboard need to be set, things like constraints, fonts, etc need to be tested. Bonus for doing stuff to get the log to use that background image from the design. log is currently acts as the date container. If we dont have the the round button views completed yet thats fine, but the constraints for and views can be set up for the bottom 3 buttons, please try to move the buttons that are there into the views you want to use, otherwise reconnect them or let me know you disconnected them.

Bonus Bonus points if you get the swipping code that goes to the 2 side views set up. so you can move those 2 views from cory's storyboard onto main while you are here

Can whoever works on this please reply on this issue with the 6 color themes that Im guessing are global to each module.

**Comment by VincentShaneFinn** [comment]
I pulled up xcode 3 hours later, after doing nothing to the tracking stuff, and I could change the bar color on the main storyboard
wtf

**Comment by CWHensley** [comment]
Wondering if this can be closed as I did this while doing issue_20
