### ISSUE TITLE
PICKERS ON ModifyAbstrasctSVC UI (Exercise Add Subview View)

### ISSUE THREAD

**Issue by VincentShaneFinn** [DrexelOMS/OvercomingMS#40]
Please do call this Xib ModifyAbstractSVC as many class will use this view.  the first 3 views to make are:
- view to hold label
- view to hold selection picker
- * maybe a view for spacing
- buttons view at the bottom

depending on how the contraints should function, everything can be in a stack view with, the buttons view can be a fixed / max height at the bottom and the other views are inside a stack view.

I don't know how we should formalize this but, theres a lot of button views throughout the project, and their constrains will always be set by whatever view it is parented to. 

Consider that every bottom buttons view should be a fixed height of 100px or something, this is just for thinking about consistency

**Comment by VincentShaneFinn** [comment]
the object library does have the picker view, just search for picker

**Comment by DrexelOMS** [comment]
a ui for this is made, but need updates and using pickers
