### ISSUE TITLE
PICKERS USED IN ModifyAbstractSVC And ExerciseAddSVC CodE

### ISSUE THREAD

**Issue by VincentShaneFinn** [DrexelOMS/OvercomingMS#41]
Note: Code for this is in the build, just some placeholder stuff and not working with pickers. Also I quickly threw together these classes and will need to be refactored so things in the appropriate classes are being used I think.

Many classes will implement this abstract class, not just one for every add page for each tracking section, but Add and Edit are pretty much the same, just one appends, and the other uses the data item to display what you are editing, and then updates that row

Needs and IBOutlet for the 3 pickers to set the values, then make sure you know how to get the selection when a button is pushed. If you give up on this issue let me know, or this should be an issue that I work with someone face to face with sometime this week

then you should have code to set the actions for the BackAndConfirmButtonSVC events

using the ExerciseRoutinesDBS that I will make,  you will be able to easily append the picker values to the db on confirm, see the current Modify Abstract SVC.

**Comment by DrexelOMS** [comment]
a draft of this has been completed and merged
