### ISSUE TITLE
Update DBT and DBS for Medication Issue_76_v2

### ISSUE THREAD

**Issue by cgl48** [DrexelOMS/OvercomingMS#76]
Make MedicationHistory DBT and DBS, update TrackingDayDBT with Medication variables

**Comment by DrexelOMS** [comment]
put this on hold for a bit and do it last

**Comment by DrexelOMS** [comment]
This first needs two DBTs

SavedMedicationDBT: Object
    @objc dynamic var MedicationName : String = ""
    @objc dynamic var TimeOfDay : Date = Date()
    @objc dynamic var MedicationAmount : Int = 0
    @objc dynamic var MedicationUOM : String = ""
    @objc dynamic var Frequency : String = "" //Conversion is MTWRFSU, U is sunday
    @objc dynamic var Active: bool = true // if true, display on the list, otherwise it is "Archived", this is used instead of deleting this item

MedicationHistoryDBT: Object
    let Medication: SavedMedicationDBT = SavedMedicationDBT()
    @objc dynamic var Taken: bool = false // if true, display on the list, otherwise it is "Archived"

the ideas is there is permanent list of saved medications, that are either active or not, like "delete" it sets it to inactive.

also need two DBS
SavedMedicationDBS and MedicationHistoryDBS

SavedMedicationDBS needs a method to add a new medication, get all the saved medications, update a saved medication, and deleteSavedMedication() NOTE: do not copy the delete code, when you delete the medication, simply set active to true, and in the get all saved medications method, you need to go through all the medication items, making a new list, skipping any that have Active = false

MedicationHistoryDBS
needs an add history item, which just takes a savedMedicationDBT as a parameter, same as update, getTodaysHistoryItems will be similar to other DBS, and there should be no way to delete it. there will need to be a method to toggleMedicationTaken, that toggles the taken bool similar the toggleFilledDate Method
