### ISSUE TITLE
Implement code for Timer

### ISSUE THREAD

**Issue by VincentShaneFinn** [DrexelOMS/OvercomingMS#9]
The goal is something where you can set the amount of time to count from, and correctly countdown to zero.

let timer = Timer.scheduledTimer(withTimeInterval: 1.0, repeats: true) { timer in
    print("Timer fired!")
}
https://www.hackingwithswift.com/articles/117/the-ultimate-guide-to-timer

This url should help with getting started. I believe this should be in some class called like timer controller that a timer view would be connected to. This way a view controller from any class could easily use, the downside for whoever is doing this and doesn't know how to use swift delegates ("not saying I'm an expert either"). But if you ever seen a video of using the tableViewControllerDelegate, we would essentially be making a custom class that works like this.
NOTE: It is ok if you just implement the timer code on a normal view controller for a scene and I can do a walkthrough to try and figure out how to do the cool stuff I describe above

You can simply test the UI update with a print statement that will be changed later to update the time. just know that the value in a timer format, and a percentage must be accessible to an observer.

something should happen when the timer is done, but the timer should not have to reach zero in order to update the time spent on that activity, what if they shut off their phone when there was 3 minutes left on the timer, but it was going for an hour, we don't want to lose their progress

**Comment by ctd58** [comment]
Countdown Timer is completed
Still TO DO:
-Stopwatch Timer
